### ISSUE TITLE
Add support or the new gpt-3.5-turbo model?

### ISSUE THREAD

**Issue by AsafMah** [SimiaCryptus/intellij-aicoder#25]
You can select it from the model list, but when using it I encounter:

![image](https://user-images.githubusercontent.com/6424271/222944766-2741bf4c-9275-4af6-9f35-aea5bd1fb723.png)

For completions.

And

![image](https://user-images.githubusercontent.com/6424271/222944775-119ff38e-5ddb-4beb-8d6c-1645b4b947be.png)

For text editing

**Comment by acharneski** [comment]
The model selection does not have any filtering logic to narrow down the selection based on use case. You might notice you can also select the "whisper" model, which is entirely irrelevant to a text completion use case. This is due to current limitations in the API, and my design intention of allowing maximal configurations and maximal flexibility.

That said, I do have some plans to add some features that take advantage of these chat models, so stay tuned!
